// NAVBAR
export { default as Navbar } from './Navbar/Navbar'
export { default as Navigation } from './Navbar/Navigation/Navigation'
export { default as Menu } from './Navbar/Menu/Menu'
export { default as MenuNavigation } from './Navbar/Menu/MenuNavigation/MenuNavigation'

export { default as Hero } from './Hero'
export { default as Stats } from './Stats'
export { default as Business } from './Business'
export { default as Billing } from './Billing'
export { default as CardDeal } from './CardDeal'
export { default as Testimonials } from './Testimonials'
export { default as Clients } from './Clients'
export { default as CTA } from './CTA'
export { default as Footer } from './Footer'